apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: harbor-config
    literals:
      - HARBOR_URL=${HARBOR_URL}
      - TLS_SECRET_NAME=${TLS_SECRET_NAME}
      - STORAGE_CLASS_NAME=${STORAGE_CLASS_NAME}
      - NFS_SERVER=${NFS_SERVER}
      - NFS_PATH=${NFS_PATH}
      - REGISTRY_SIZE=${REGISTRY_SIZE}

resources:
  - pv.template.yaml

replacements:
  - source:
      kind: ConfigMap
      name: harbor-config
      fieldPath: data.HARBOR_URL
    targets:
      - select:
          kind: HelmRelease
        fieldPaths:
          - spec.values.expose.ingress.hosts.core
          - spec.values.externalURL
  - source:
      kind: ConfigMap
      name: harbor-config
      fieldPath: data.TLS_SECRET_NAME
    targets:
      - select:
          kind: HelmRelease
        fieldPaths:
          - spec.values.expose.tls.secret.secretName
  - source:
      kind: ConfigMap
      name: harbor-config
      fieldPath: data.STORAGE_CLASS_NAME
    targets:
      - select:
          kind: HelmRelease
        fieldPaths:
          - spec.values.persistence.persistentVolumeClaim.registry.storageClass
  - source:
      kind: ConfigMap
      name: harbor-config
      fieldPath: data.NFS_SERVER
    targets:
      - select:
          kind: PersistentVolume
        fieldPaths:
          - spec.nfs.server
  - source:
      kind: ConfigMap
      name: harbor-config
      fieldPath: data.NFS_PATH
    targets:
      - select:
          kind: PersistentVolume
        fieldPaths:
          - spec.nfs.path 