apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-registry-pv
spec:
  capacity:
    storage: 120Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: truenas-nfs
  mountOptions:
    - nfsvers=3
    - tcp
    - nolock
    - rw
  nfs:
    path: ${NFS_PATH}
    server: ${NFS_SERVER} 