apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: truenas-nfs
provisioner: k8s.io/no-provisioner
parameters: {}
mountOptions:
  - nfsvers=3
  - tcp
  - nolock
volumeBindingMode: WaitForFirstConsumer 