apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-workflows
    targetRevision: 0.45.7
    helm:
      values: |
        server:
          extraArgs:
            - --auth-mode=server
          serviceType: NodePort
          nodePort: 30600
        workflow:
          serviceAccount:
            create: true
            name: argo-workflow
        controller:
          workflowNamespaces:
            - argo
            - discord-bot-development
            - discord-bot-production
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 