apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: 0.29.1
    helm:
      values: |
        server:
          dev:
            enabled: false
          standalone:
            enabled: true
            config: |
              ui = true
              listener "tcp" {
                tls_disable = 1
                address = "[::]:8200"
                cluster_address = "[::]:8201"
              }
              storage "file" {
                path = "/vault/data"
              }
          service:
            enabled: true
            type: NodePort
            nodePort: 30900
          dataStorage:
            enabled: true
            size: 10Gi
          auditStorage:
            enabled: true
            size: 10Gi
        ui:
          enabled: true
          serviceType: NodePort
          serviceNodePort: 30901
          externalPort: 8200
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 