apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
  namespace: argocd
data:
  kustomized-helm.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: kustomized-helm
    spec:
      version: v1.0
      generate:
        command: [sh, -c]
        args:
          - |
            kustomize build . | 
            helm template harbor harbor/harbor --include-crds \
              --values values.template.yaml \
              --namespace default | 
            kustomize build - 